[package]
name = "spell"
version = "0.1.0"
authors = ["elsid <elsid.mail@gmail.com>"]
edition = "2018"

[dependencies]
env_logger = "0.8.3"
log = "0.4.14"
rand = { version = "0.8.3", features = ["small_rng"] }
piston_window = { version = "0.113.0", optional = true }
pistoncore-glfw_window = { version = "0.71.0", optional = true }
conrod_core = { version = "0.73.0", optional = true }
conrod_piston = { version = "0.73.0", optional = true }
parry2d-f64 = "0.4.1"
serde = { version = "1.0.125", features = ["derive"] }
bincode = "1.3.3"
tokio = { version = "1.5.0", features = ["net", "rt", "time"] }
clap = "3.0.0-beta.2"
lz4_flex = "0.7.5"
nalgebra = "0.26.2"
ctrlc = "3.1.9"

[dev-dependencies]
portpicker = "0.1.0"

[features]
default = []
render = ["piston_window", "pistoncore-glfw_window", "conrod_core", "conrod_piston"]
