[package]
name = "spell"
version = "0.1.0"
authors = ["elsid <elsid.mail@gmail.com>"]
edition = "2018"

[dependencies]
itertools = "0.10.0"
env_logger = "0.8.3"
log = "0.4.14"
rand = { version = "0.8.3", features = ["small_rng"] }
piston = "0.52.1"
piston2d-graphics = "0.39.0"
pistoncore-glfw_window = "0.71.0"
piston2d-opengl_graphics = "0.77.0"
