[package]
name = "spell"
version = "0.1.0"
authors = ["elsid <elsid.mail@gmail.com>"]
edition = "2018"

[dependencies]
itertools = "0.10.0"
env_logger = "0.8.3"
log = "0.4.14"
rand = { version = "0.8.3", features = ["small_rng"] }
piston = { version = "0.52.1", optional = true }
piston2d-graphics = { version = "0.39.0", optional = true }
pistoncore-glfw_window = { version = "0.71.0", optional = true }
piston2d-opengl_graphics = { version = "0.77.0", optional = true }
parry2d-f64 = "0.1.2"
serde = { version = "1.0.123", features = ["derive"] }
bincode = "1.3.2"
tokio = { version = "1.2.0", features = ["net", "rt", "time"] }
clap = "3.0.0-beta.2"
lz4_flex = "0.7.5"

[features]
default = []
render = ["piston", "piston2d-graphics", "pistoncore-glfw_window", "piston2d-opengl_graphics"]
