on: [push, pull_request]

name: CI

jobs:
  build_default:
    name: Build default
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --bins

  build_all:
    name: Build all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: sudo apt install -y libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-features --all-targets

  test_default:
    name: Tests default
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: 1
      RUST_LOG: debug
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test

  test_all:
    name: Tests all
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: 1
      RUST_LOG: debug
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: sudo apt install -y libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features

  test_all_release:
    name: Tests all release
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: 1
      RUST_LOG: debug
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: sudo apt install -y libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --release

  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy default
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --bins -- -D warnings

  clippy_all:
    name: Clippy all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add clippy
      - run: sudo apt install -y libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-features --all-targets -- -D warnings
